### ISSUE TITLE
"RNCViewPager" was not found in the UIManager. [RN 0.61.2] [Android]

### ISSUE THREAD

**Issue by mistikk** [react-native-community/react-native-viewpager#72]
# Bug

![image](https://user-images.githubusercontent.com/8211075/66558447-3928bb00-eb5c-11e9-97ed-c4364041c882.png)

## Environment info

react-native: 0.61.2
react-native-viewpager: 2.0.1

**Comment by ferrannp** [comment]
For what I see you are using https://github.com/ptomasroos/react-native-scrollable-tab-view. See https://github.com/ptomasroos/react-native-scrollable-tab-view/blob/master/index.js#L13. `ViewPagerAndroid` is not part of react-native core anymore. You should open an issue to that repo and ask to update the library to use https://github.com/react-native-community/react-native-viewpager instead.

**Comment by mistikk** [comment]
I am not using ptomasroos/react-native-scrollable-tab-view. I forked and updated with react-native-community/react-native-viewpager.
You can see forked repo https://github.com/esteemapp/react-native-scrollable-tab-view

**Comment by ferrannp** [comment]
If you create a new app with `react-native init`, does the viewpager here works for you?

**Comment by baleo-it** [comment]
@mistikk RN > 0.60, you need to do
```
cd ios
pod install --repo-update
`
``

**Comment by mistikk** [comment]
@baleo-it i already run pod install

**Comment by ferrannp** [comment]
Can you provide a repository to reproduce your issue?

**Comment by leecz** [comment]
same issue

**Comment by superandrew213** [comment]
@ferrannp here is the repo https://github.com/superandrew213/viewpagertest.

This uses the latest version of `react-native-scrollable-tab-view` from github which uses `@react-native-community/viewpager`

https://github.com/ptomasroos/react-native-scrollable-tab-view/commits/master

**Comment by ferrannp** [comment]
@superandrew213 if you install `@react-native-community/viewpager` it works. I think the problem is in https://github.com/ptomasroos/react-native-scrollable-tab-view/blob/master/package.json#L27-L29. Can you try and add `@react-native-community/viewpager` as `peerDependency` ?

**Comment by superandrew213** [comment]
@ferrannp I can confirm that it works if you install `@react-native-community/viewpager`. 

`@react-native-community/viewpager` has been added as a dependency to `react-native-scrollable-tab-view`. Why add it as a peer dependency?

**Comment by superandrew213** [comment]
@ferrannp `@react-native-community/viewpager` should be working even if it has been added as a dependency. This is probably a linking issue?

**Comment by Domtry** [comment]
Any solution proposal did not solve my problem

this is my package.js config
-----
"dependencies": {
    "react": "16.9.0",
    "react-native": "0.61.4",
    "react-native-elements": "^1.2.7",
    "react-native-input-scroll-view": "^1.9.5",
    "react-native-navigation": "^3.5.1",
    "react-native-scrollable-tab-view": "^1.0.0",
    "react-native-vector-icons": "^6.6.0"
  },
  "devDependencies": {
    "@babel/core": "7.7.2",
    "@babel/runtime": "7.7.2",
    "@react-native-community/eslint-config": "0.0.5",
    "babel-jest": "24.9.0",
    "jest": "24.9.0",
    "metro-react-native-babel-preset": "0.56.3",
    "react-test-renderer": "16.9.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by jakajacky** [comment]
i have the same error,  RN = 0.60.5,  Platform = iOS/Android
And fixed by **[Manual linking](https://github.com/react-native-community/react-native-viewpager#manual-linking)** guide, both iOS,Android work fine.

1.  ` npm i @react-native-community/viewpager`
2. on iOS, adding this to your Podfile:
`pod 'react-native-viewpager', :path => '../node_modules/@react-native-community/viewpager'`
then 
`cd ios`
`pod install`
3. on Android, make the following changes:
### android/settings.gradle
```
include ':@react-native-community_viewpager'
project(':@react-native-community_viewpager').projectDir = new File(rootProject.projectDir, '../node_modules/@react-native-community/viewpager/android')
```
### android/app/build.gradle
```
dependencies {
   ...
   implementation project(':@react-native-community_viewpager')
}
```
### android/app/src/main/.../MainApplication.java
On top, where imports are:

`import com.reactnativecommunity.viewpager.RNCViewPagerPackage;`

Add the RNCViewPagerPackage class to your list of exported packages.

```
@Override
protected List<ReactPackage> getPackages() {
  return Arrays.<ReactPackage>asList(
    new MainReactPackage(),
    new RNCViewPagerPackage()
  );
```

**Comment by igorbrandao** [comment]
Any solution for those using a non ejected expo app?

**Comment by sytolk** [comment]
I have the same issue on Android (iOS works) RN 0.60.6
dependencies:
"react-native-best-viewpager": "^1.0.4", -> https://github.com/abbasmoosavi/react-native-best-viewpager/blob/master/package.json#L39
"@react-native-community/viewpager": "^3.3.0", <- adding this line in my project package.json fix this issue
Maybe this issue is yarn related ??

**Comment by DrFlink** [comment]
This worked for me:

RN-cli: 2.0.1
RN: 0.61.5

I tried linking the package, but that didn't help.
I tried manual linking and saw that the RNCViewPagerPackage was missing in:
android/app/src/main/java/com/[...]/MainApplication.java

I added the package (last line before return):
`       @Override
        protected List<ReactPackage> getPackages() {
          @SuppressWarnings("UnnecessaryLocalVariable")
          List<ReactPackage> packages = new PackageList(this).getPackages();
          // Packages that cannot be autolinked yet can be added manually here, for example:
          // packages.add(new MyReactNativePackage());
          packages.add(new RNCViewPagerPackage()); // <--------- Here we go
          return packages;
        }`

I emptied cache and ran: react-native run-android.

**Comment by UnnikrishnanBhargavakurup** [comment]
still not working any suggestions

**Comment by olkunmustafa** [comment]
> i have the same error, RN = 0.60.5, Platform = iOS/Android
> And fixed by **[Manual linking](https://github.com/react-native-community/react-native-viewpager#manual-linking)** guide, both iOS,Android work fine.
> 
> 1. ` npm i @react-native-community/viewpager`
> 2. on iOS, adding this to your Podfile:
>    `pod 'react-native-viewpager', :path => '../node_modules/@react-native-community/viewpager'`
>    then
>    `cd ios`
>    `pod install`
> 3. on Android, make the following changes:
> 
> ### android/settings.gradle
> ```
> include ':@react-native-community_viewpager'
> project(':@react-native-community_viewpager').projectDir = new File(rootProject.projectDir, '../node_modules/@react-native-community/viewpager/android')
> ```
> 
> ### android/app/build.gradle
> ```
> dependencies {
>    ...
>    implementation project(':@react-native-community_viewpager')
> }
> ```
> 
> ### android/app/src/main/.../MainApplication.java
> On top, where imports are:
> 
> `import com.reactnativecommunity.viewpager.RNCViewPagerPackage;`
> 
> Add the RNCViewPagerPackage class to your list of exported packages.
> 
> ```
> @Override
> protected List<ReactPackage> getPackages() {
>   return Arrays.<ReactPackage>asList(
>     new MainReactPackage(),
>     new RNCViewPagerPackage()
>   );
> ```

It is the solution.

**Comment by tiagobbraga** [comment]
Modification in the last step using with RN 0.63.2 and React 16.13.1


Instead of
```
@Override
protected List<ReactPackage> getPackages() {
  return Arrays.<ReactPackage>asList(
    new MainReactPackage(),
    new RNCViewPagerPackage()
  );
```

this
```
protected List<ReactPackage> getPackages() {
          @SuppressWarnings("UnnecessaryLocalVariable")
          List<ReactPackage> packages = new PackageList(this).getPackages();
          packages.add(new RNCViewPagerPackage());
          return packages;
        }
```

> i have the same error, RN = 0.60.5, Platform = iOS/Android
> And fixed by **[Manual linking](https://github.com/react-native-community/react-native-viewpager#manual-linking)** guide, both iOS,Android work fine.
> 
> 1. ` npm i @react-native-community/viewpager`
> 2. on iOS, adding this to your Podfile:
>    `pod 'react-native-viewpager', :path => '../node_modules/@react-native-community/viewpager'`
>    then
>    `cd ios`
>    `pod install`
> 3. on Android, make the following changes:
> 
> ### android/settings.gradle
> ```
> include ':@react-native-community_viewpager'
> project(':@react-native-community_viewpager').projectDir = new File(rootProject.projectDir, '../node_modules/@react-native-community/viewpager/android')
> ```
> 
> ### android/app/build.gradle
> ```
> dependencies {
>    ...
>    implementation project(':@react-native-community_viewpager')
> }
> ```
> 
> ### android/app/src/main/.../MainApplication.java
> On top, where imports are:
> 
> `import com.reactnativecommunity.viewpager.RNCViewPagerPackage;`
> 
> Add the RNCViewPagerPackage class to your list of exported packages.
> 
> ```
> @Override
> protected List<ReactPackage> getPackages() {
>   return Arrays.<ReactPackage>asList(
>     new MainReactPackage(),
>     new RNCViewPagerPackage()
>   );
> ```

**Comment by biomancer** [comment]
In my case just adding @react-native-community/viewpager explicitly to dependencies in package.json of my project solved the issue, no manual linking was required after that (RN 0.64.0)

**Comment by kevinblu** [comment]
> new RNCViewPagerPackage()

It really worked!!!!!! Thank you 3000!

Little tips: if you use DefaultHardwareBackBtnHandler interface to init your reactActivity, you might need to add RNCViewPagerPackage like this
`mReactInstanceManager = ReactInstanceManager.builder()
                .setApplication(getActivity().getApplication())
                .........
                .addPackage(new RNCViewPagerPackage())
                .......
                .build();
`

**Comment by andresribeiro** [comment]
```shell
yarn add @react-native-community/viewpager
react-native link @react-native-community/viewpager
```

This worked for me. React Native version 0.64.2

**Comment by troZee** [comment]
> ```shell
> yarn add @react-native-community/viewpager
> react-native link @react-native-community/viewpager
> ```
> 
> This worked for me. React Native version 0.64.2

You are using wrong package name. Please use this commend `yarn add react-native-pager-view`. You don't need to link this library, bc cli has autolinking module.

**Comment by bracketsberlin** [comment]
I have the same issue under Android RN 0.64.2.

I am using the [<TabView>](https://github.com/satya164/react-native-tab-view) component and just migrated to 3.1.1. Once I try displaying the component, I'm getting the following error message:
`"RNCViewPager" was not found in the UIManager.`

My package.json lists the following packages:
`
"@react-native-community/viewpager": "^5.0.11",
"react-native-pager-view": "^5.4.1",
"react-native-tab-view": "^3.1.1",
`

As suggested by @troZee , I ran:
`
yarn add react-native-pager-view
react-native link react-native-pager-view
`

I'd love to get some pointers - I just can't make it work!

**Comment by hpardess** [comment]
I have the same issue while running my app in Android emulator.
<img width="253" alt="Screen Shot 2021-12-20 at 10 29 20 PM" src="https://user-images.githubusercontent.com/6196491/146811842-6828ead6-5530-4ac8-9af8-980fe50490bb.png">

ERROR  Invariant Violation: requireNativeComponent: "RNCViewPager" was not found in the UIManager.

This error is located at:
    in RNCViewPager (at PagerView.tsx:145)
    in PagerView (at createAnimatedComponent.js:242)
    in AnimatedComponent (at createAnimatedComponent.js:295)
    in AnimatedComponentWrapper (at PagerViewAdapter.tsx:123)
    in PagerViewAdapter (at TabView.tsx:79)
    in RCTView (at View.js:32)
    in View (at TabView.tsx:78)



Here is my project dependencies:
"react": "17.0.2",
"react-native": "0.66.4",
"react-native-tab-view": "^3.1.1",

**Comment by maxizhukov** [comment]
Same issue in ios RN 64.1

**Comment by Furqan02** [comment]
same problem

**Comment by Furqan02** [comment]
run : npm i react-native-pager-view

**Comment by scottmas** [comment]
Make sure you do pod install and then a full native rebuild after installing react-native-pager-view since it has native dependencies

**Comment by OmarBakr2020** [comment]
This is my solution for this issue, You can check it out

https://stackoverflow.com/a/75277939/10504018

**Comment by moin-nimblechapps** [comment]
Same issue in RN:  73.4

@react-navigation/native-stack": "^6.9.18",
react-navigation/material-top-tabs": "^6.6.12"
 "react-native-pager-view": "^6.2.3"
"react-native-tab-view": "^3.5.2"

please help to solve this issue
